Fix repository-convention: handle spaces in file names
java.lang.IllegalArgumentException: Illegal character in path at index 90: https://github.com/TWiStErRob/net.twisterrob.cinema/blob/master/.github/workflows/Generate random data.yml
        at java.base/java.net.URI.create(URI.java:883)
        at Validate_main.validateFiles$webUrl(validate.main.kts:205)
        at Validate_main.access$validateFiles$webUrl(validate.main.kts:1)
        at Validate_main$validateFiles$4.invoke(validate.main.kts:212)
        at Validate_main$validateFiles$4.invoke(validate.main.kts:212)
        at Validate_main.validateGradleWrapper(validate.main.kts:302)
        at Validate_main$validateGradleWrapper$1.invokeSuspend(validate.main.kts)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.URISyntaxException: Illegal character in path at index 90: https://github.com/TWiStErRob/net.twisterrob.cinema/blob/master/.github/workflows/Generate random data.yml
        at java.base/java.net.URI$Parser.fail(URI.java:2915)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
        at java.base/java.net.URI$Parser.parse(URI.java:3116)
        at java.base/java.net.URI.<init>(URI.java:600)
        at java.base/java.net.URI.create(URI.java:881)
        ... 12 more